### ISSUE TITLE
Немає відступу між опціями жанру

### ISSUE THREAD

**Issue by rosset-nocpes** [hikka-io/bug-reports#2]
![Screenshot_20240113_202348](https://github.com/hikka-io/bug-reports/assets/53056080/cc4d68b0-02f5-482d-bc37-16e98421d3dc)

**Comment by rosset-nocpes** [comment]
## Пропозиція:
### Об'єднувати опції, які поруч обрані: 
![Screenshot_20240113_205301](https://github.com/hikka-io/bug-reports/assets/53056080/9736d5a2-bb54-4b76-8937-3ce9c23817c6)

**Comment by volbil** [comment]
Проблема вирішена
